version: '3.5'

services:

  backtor-restic:
    build: .
    ports:
      - 7070:7070
    environment:
      - RESTIC_PASSWORD=123
      - LOG_LEVEL=debug
      - SOURCE_DATA_PATH=/backup-source/TESTFILE
      - REPO_DIR=/backup-repo
      - CONDUCTOR_API_URL=http://172.20.10.2:8080/api
      # - PRE_BACKUP_COMMAND=dd if=/dev/zero of=/backup-source/TESTFILE bs=100MB count=2
      # - POST_BACKUP_COMMAND=rm /backup-source/TESTFILE
